sender_receiver = {
    "naomi@shanbaypro.com": [
        "hyatt@shanbaypro.com",
        "kamal@shanbaypro.com",
        "may@shanbaypro.com",
        "karina@shanbaypro.com",
        "cassady@shanbaypro.com",
    ],
    "daria@shanbaypro.com": [
        "demetrius@shanbaypro.com",
        "kiann@shanbaypro.com",
        "shea@shanbaypro.com",
        "cheryl@shanbaypro.com",
        "stone@shanbaypro.com",
        "sahil@shanbaypro.com",
    ],
    "quynn@shanbaypro.com": [
        "adam@shanbaypro.com",
        "yardley@shanbaypro.com",
        "cadman@shanbaypro.com",
        "mohammad@shanbaypro.com",
        "hyatt@shanbaypro.com",
        "orlando@shanbaypro.com",
    ],
    "shaine@shanbaypro.com": [
        "amanda@shanbaypro.com",
        "george@shanbaypro.com",
        "lev@shanbaypro.com",
        "richard@shanbaypro.com",
        "kamal@shanbaypro.com",
        "martina@shanbaypro.com",
        "colton@shanbaypro.com",
    ],
    "jack@shanbaypro.com": ["sage@shanbaypro.com"],
    "mason@shanbaypro.com": [
        "christine@shanbaypro.com",
        "zenaida@shanbaypro.com",
        "sonia@shanbaypro.com",
        "eshan@shanbaypro.com",
    ],
    "ruth@shanbaypro.com": [
        "holmes@shanbaypro.com",
        "burton@shanbaypro.com",
        "raja@shanbaypro.com",
        "martin@shanbaypro.com",
        "hoyt@shanbaypro.com",
        "karina@shanbaypro.com",
    ],
    "jackson@shanbaypro.com": [
        "ehlana@shanbaypro.com",
        "sonia@shanbaypro.com",
        "oliver@shanbaypro.com",
    ],
    "ingrid@shanbaypro.com": [
        "rama@shanbaypro.com",
        "byron@shanbaypro.com",
        "theodore@shanbaypro.com",
        "tatiana@shanbaypro.com",
        "eshan@shanbaypro.com",
    ],
    "josiah@shanbaypro.com": ["hedda@shanbaypro.com", "zeus@shanbaypro.com"],
    "graham@shanbaypro.com": [
        "rama@shanbaypro.com",
        "moses@shanbaypro.com",
        "miriam@shanbaypro.com",
        "maite@shanbaypro.com",
        "jayesh@shanbaypro.com",
    ],
    "alexander@shanbaypro.com": [
        "cheng@shanbaypro.com",
        "hedwig@shanbaypro.com",
        "sage@shanbaypro.com",
        "nomlanga@shanbaypro.com",
    ],
    "neil@shanbaypro.com": [
        "simone@shanbaypro.com",
        "daniel@shanbaypro.com",
        "byron@shanbaypro.com",
        "cheng@shanbaypro.com",
    ],
    "zenaida@shanbaypro.com": [
        "elton@shanbaypro.com",
        "amanda@shanbaypro.com",
        "mason@shanbaypro.com",
        "byron@shanbaypro.com",
        "oliver@shanbaypro.com",
        "simone@shanbaypro.com",
    ],
    "moses@shanbaypro.com": [
        "alexandra@shanbaypro.com",
        "phoebe@shanbaypro.com",
        "karina@shanbaypro.com",
        "graham@shanbaypro.com",
        "maite@shanbaypro.com",
        "kay@shanbaypro.com",
        "amanda@shanbaypro.com",
        "kiann@shanbaypro.com",
    ],
    "kamal@shanbaypro.com": [
        "shaine@shanbaypro.com",
        "tatum@shanbaypro.com",
        "naomi@shanbaypro.com",
        "adam@shanbaypro.com",
        "stone@shanbaypro.com",
    ],
    "carol@shanbaypro.com": [
        "hoyt@shanbaypro.com",
        "oliver@shanbaypro.com",
        "lev@shanbaypro.com",
    ],
    "aladdin@shanbaypro.com": [
        "cheryl@shanbaypro.com",
        "george@shanbaypro.com",
        "paki@shanbaypro.com",
        "nomlanga@shanbaypro.com",
        "kim@shanbaypro.com",
    ],
    "matthew@shanbaypro.com": [
        "eldece@shanbaypro.com",
        "mohammad@shanbaypro.com",
        "preston@shanbaypro.com",
    ],
    "jared@shanbaypro.com": [
        "byron@shanbaypro.com",
        "mohammad@shanbaypro.com",
        "bree@shanbaypro.com",
        "branden@shanbaypro.com",
    ],
    "tatum@shanbaypro.com": [
        "amanda@shanbaypro.com",
        "kim@shanbaypro.com",
        "dustin@shanbaypro.com",
        "daniel@shanbaypro.com",
        "kamal@shanbaypro.com",
        "hunter@shanbaypro.com",
    ],
    "sage@shanbaypro.com": [
        "eshan@shanbaypro.com",
        "alexander@shanbaypro.com",
        "richard@shanbaypro.com",
        "ehlana@shanbaypro.com",
        "jack@shanbaypro.com",
        "branden@shanbaypro.com",
        "sloane@shanbaypro.com",
        "martina@shanbaypro.com",
        "yardley@shanbaypro.com",
    ],
    "theodore@shanbaypro.com": [
        "ingrid@shanbaypro.com",
        "bree@shanbaypro.com",
        "susan@shanbaypro.com",
        "sybil@shanbaypro.com",
        "daniel@shanbaypro.com",
        "kay@shanbaypro.com",
        "preston@shanbaypro.com",
        "shea@shanbaypro.com",
    ],
    "mohammad@shanbaypro.com": [
        "quynn@shanbaypro.com",
        "branden@shanbaypro.com",
        "jared@shanbaypro.com",
        "matthew@shanbaypro.com",
        "ezekiel@shanbaypro.com",
    ],
    "susan@shanbaypro.com": [
        "eldece@shanbaypro.com",
        "george@shanbaypro.com",
        "theodore@shanbaypro.com",
        "martina@shanbaypro.com",
    ],
    "bree@shanbaypro.com": [
        "alexandra@shanbaypro.com",
        "jared@shanbaypro.com",
        "theodore@shanbaypro.com",
        "sahil@shanbaypro.com",
    ],
    "miriam@shanbaypro.com": ["graham@shanbaypro.com", "richard@shanbaypro.com"],
    "demetrius@shanbaypro.com": [
        "jayesh@shanbaypro.com",
        "daria@shanbaypro.com",
        "mufutau@shanbaypro.com",
        "adam@shanbaypro.com",
    ],
    "martin@shanbaypro.com": [
        "ruth@shanbaypro.com",
        "cadman@shanbaypro.com",
        "ehlana@shanbaypro.com",
    ],
    "elton@shanbaypro.com": [
        "lamar@shanbaypro.com",
        "richard@shanbaypro.com",
        "zenaida@shanbaypro.com",
        "adam@shanbaypro.com",
        "yardley@shanbaypro.com",
    ],
    "may@shanbaypro.com": [
        "naomi@shanbaypro.com",
        "tatiana@shanbaypro.com",
        "cassady@shanbaypro.com",
    ],
    "holmes@shanbaypro.com": [
        "nomlanga@shanbaypro.com",
        "lev@shanbaypro.com",
        "hedwig@shanbaypro.com",
        "ruth@shanbaypro.com",
        "zephania@shanbaypro.com",
        "george@shanbaypro.com",
    ],
    "rama@shanbaypro.com": [
        "yardley@shanbaypro.com",
        "ingrid@shanbaypro.com",
        "graham@shanbaypro.com",
        "francesca@shanbaypro.com",
        "dolan@shanbaypro.com",
        "shea@shanbaypro.com",
    ],
    "hoyt@shanbaypro.com": [
        "orlando@shanbaypro.com",
        "martina@shanbaypro.com",
        "ruth@shanbaypro.com",
        "carol@shanbaypro.com",
        "ella@shanbaypro.com",
        "hamza@shanbaypro.com",
    ],
    "zeus@shanbaypro.com": [
        "josiah@shanbaypro.com",
        "ezekiel@shanbaypro.com",
        "nomlanga@shanbaypro.com",
    ],
    "hyatt@shanbaypro.com": [
        "quynn@shanbaypro.com",
        "raja@shanbaypro.com",
        "joshua@shanbaypro.com",
        "naomi@shanbaypro.com",
    ],
    "karina@shanbaypro.com": [
        "naomi@shanbaypro.com",
        "ruth@shanbaypro.com",
        "branden@shanbaypro.com",
        "moses@shanbaypro.com",
        "hedda@shanbaypro.com",
        "adam@shanbaypro.com",
        "burton@shanbaypro.com",
    ],
    "sonia@shanbaypro.com": [
        "mason@shanbaypro.com",
        "preston@shanbaypro.com",
        "jackson@shanbaypro.com",
    ],
    "cadman@shanbaypro.com": ["martin@shanbaypro.com", "quynn@shanbaypro.com"],
    "orlando@shanbaypro.com": [
        "quynn@shanbaypro.com",
        "hoyt@shanbaypro.com",
        "yardley@shanbaypro.com",
    ],
    "ella@shanbaypro.com": [
        "sahil@shanbaypro.com",
        "hoyt@shanbaypro.com",
        "eldece@shanbaypro.com",
        "hunter@shanbaypro.com",
        "shea@shanbaypro.com",
        "kiann@shanbaypro.com",
    ],
    "byron@shanbaypro.com": [
        "zenaida@shanbaypro.com",
        "ingrid@shanbaypro.com",
        "eshan@shanbaypro.com",
        "stone@shanbaypro.com",
        "neil@shanbaypro.com",
        "jared@shanbaypro.com",
    ],
    "ursula@shanbaypro.com": [
        "phoebe@shanbaypro.com",
        "ehlana@shanbaypro.com",
        "zephania@shanbaypro.com",
    ],
    "oliver@shanbaypro.com": [
        "jackson@shanbaypro.com",
        "zenaida@shanbaypro.com",
        "colton@shanbaypro.com",
        "carol@shanbaypro.com",
    ],
    "maite@shanbaypro.com": [
        "colton@shanbaypro.com",
        "moses@shanbaypro.com",
        "graham@shanbaypro.com",
        "joshua@shanbaypro.com",
        "zephania@shanbaypro.com",
        "daniel@shanbaypro.com",
    ],
    "branden@shanbaypro.com": [
        "sage@shanbaypro.com",
        "jared@shanbaypro.com",
        "mohammad@shanbaypro.com",
        "karina@shanbaypro.com",
        "sybil@shanbaypro.com",
        "francesca@shanbaypro.com",
    ],
    "sybil@shanbaypro.com": [
        "daniel@shanbaypro.com",
        "branden@shanbaypro.com",
        "theodore@shanbaypro.com",
        "alexandra@shanbaypro.com",
        "richard@shanbaypro.com",
    ],
    "sloane@shanbaypro.com": [
        "sage@shanbaypro.com",
        "francesca@shanbaypro.com",
        "martina@shanbaypro.com",
        "adam@shanbaypro.com",
        "simone@shanbaypro.com",
    ],
    "cheryl@shanbaypro.com": [
        "cade@shanbaypro.com",
        "richard@shanbaypro.com",
        "daria@shanbaypro.com",
        "aladdin@shanbaypro.com",
        "francesca@shanbaypro.com",
        "phoebe@shanbaypro.com",
        "burton@shanbaypro.com",
        "sahil@shanbaypro.com",
    ],
    "grady@shanbaypro.com": [
        "cassady@shanbaypro.com",
        "isaac@shanbaypro.com",
        "raja@shanbaypro.com",
    ],
    "zephania@shanbaypro.com": [
        "ursula@shanbaypro.com",
        "maite@shanbaypro.com",
        "holmes@shanbaypro.com",
        "curran@shanbaypro.com",
        "kiann@shanbaypro.com",
    ],
    "george@shanbaypro.com": [
        "aladdin@shanbaypro.com",
        "holmes@shanbaypro.com",
        "christine@shanbaypro.com",
        "francesca@shanbaypro.com",
        "shaine@shanbaypro.com",
        "susan@shanbaypro.com",
        "amos@shanbaypro.com",
    ],
    "paki@shanbaypro.com": [
        "aladdin@shanbaypro.com",
        "phoebe@shanbaypro.com",
        "daniel@shanbaypro.com",
        "simone@shanbaypro.com",
        "chao@shanbaypro.com",
    ],
    "martina@shanbaypro.com": [
        "sloane@shanbaypro.com",
        "shaine@shanbaypro.com",
        "susan@shanbaypro.com",
        "sage@shanbaypro.com",
        "hoyt@shanbaypro.com",
    ],
    "joshua@shanbaypro.com": [
        "hyatt@shanbaypro.com",
        "cassady@shanbaypro.com",
        "maite@shanbaypro.com",
    ],
    "daniel@shanbaypro.com": [
        "paki@shanbaypro.com",
        "adam@shanbaypro.com",
        "maite@shanbaypro.com",
        "theodore@shanbaypro.com",
        "neil@shanbaypro.com",
        "tatum@shanbaypro.com",
        "sybil@shanbaypro.com",
        "francesca@shanbaypro.com",
        "stone@shanbaypro.com",
    ],
    "colton@shanbaypro.com": [
        "burton@shanbaypro.com",
        "eldece@shanbaypro.com",
        "shaine@shanbaypro.com",
        "lamar@shanbaypro.com",
        "oliver@shanbaypro.com",
        "maite@shanbaypro.com",
        "isaac@shanbaypro.com",
        "hamza@shanbaypro.com",
    ],
    "richard@shanbaypro.com": [
        "sybil@shanbaypro.com",
        "shaine@shanbaypro.com",
        "miriam@shanbaypro.com",
        "jayesh@shanbaypro.com",
        "sage@shanbaypro.com",
        "elton@shanbaypro.com",
        "cheryl@shanbaypro.com",
        "mufutau@shanbaypro.com",
        "cheng@shanbaypro.com",
        "sahil@shanbaypro.com",
    ],
    "alexandra@shanbaypro.com": [
        "sybil@shanbaypro.com",
        "moses@shanbaypro.com",
        "bree@shanbaypro.com",
        "cade@shanbaypro.com",
    ],
    "hunter@shanbaypro.com": [
        "tatum@shanbaypro.com",
        "ella@shanbaypro.com",
        "cassady@shanbaypro.com",
    ],
    "francesca@shanbaypro.com": [
        "branden@shanbaypro.com",
        "daniel@shanbaypro.com",
        "rama@shanbaypro.com",
        "cheryl@shanbaypro.com",
        "sloane@shanbaypro.com",
        "george@shanbaypro.com",
    ],
    "hedda@shanbaypro.com": [
        "kiann@shanbaypro.com",
        "karina@shanbaypro.com",
        "josiah@shanbaypro.com",
        "amanda@shanbaypro.com",
        "lamar@shanbaypro.com",
    ],
    "mufutau@shanbaypro.com": [
        "demetrius@shanbaypro.com",
        "christine@shanbaypro.com",
        "richard@shanbaypro.com",
        "hamza@shanbaypro.com",
    ],
    "adam@shanbaypro.com": [
        "karina@shanbaypro.com",
        "sloane@shanbaypro.com",
        "demetrius@shanbaypro.com",
        "elton@shanbaypro.com",
        "quynn@shanbaypro.com",
        "kamal@shanbaypro.com",
        "daniel@shanbaypro.com",
        "jayesh@shanbaypro.com",
    ],
    "simone@shanbaypro.com": [
        "hamza@shanbaypro.com",
        "zenaida@shanbaypro.com",
        "paki@shanbaypro.com",
        "sloane@shanbaypro.com",
        "neil@shanbaypro.com",
        "jerry@shanbaypro.com",
    ],
    "dolan@shanbaypro.com": ["rama@shanbaypro.com", "raya@shanbaypro.com"],
    "raja@shanbaypro.com": [
        "amos@shanbaypro.com",
        "ruth@shanbaypro.com",
        "hyatt@shanbaypro.com",
        "grady@shanbaypro.com",
    ],
    "jerry@shanbaypro.com": [
        "simone@shanbaypro.com",
        "ehlana@shanbaypro.com",
        "burton@shanbaypro.com",
    ],
    "kay@shanbaypro.com": [
        "moses@shanbaypro.com",
        "theodore@shanbaypro.com",
        "isaac@shanbaypro.com",
    ],
    "curran@shanbaypro.com": ["hedwig@shanbaypro.com", "zephania@shanbaypro.com"],
    "preston@shanbaypro.com": [
        "matthew@shanbaypro.com",
        "isaac@shanbaypro.com",
        "theodore@shanbaypro.com",
        "sonia@shanbaypro.com",
    ],
    "yardley@shanbaypro.com": [
        "elton@shanbaypro.com",
        "sage@shanbaypro.com",
        "orlando@shanbaypro.com",
        "quynn@shanbaypro.com",
        "rama@shanbaypro.com",
    ],
    "ehlana@shanbaypro.com": [
        "martin@shanbaypro.com",
        "jackson@shanbaypro.com",
        "sage@shanbaypro.com",
        "ursula@shanbaypro.com",
        "jerry@shanbaypro.com",
    ],
    "amanda@shanbaypro.com": [
        "nomlanga@shanbaypro.com",
        "moses@shanbaypro.com",
        "hedda@shanbaypro.com",
        "christine@shanbaypro.com",
        "shaine@shanbaypro.com",
        "zenaida@shanbaypro.com",
        "tatum@shanbaypro.com",
    ],
    "dustin@shanbaypro.com": [
        "eshan@shanbaypro.com",
        "tatum@shanbaypro.com",
        "isaac@shanbaypro.com",
    ],
    "christine@shanbaypro.com": [
        "isaac@shanbaypro.com",
        "eshan@shanbaypro.com",
        "mason@shanbaypro.com",
        "george@shanbaypro.com",
        "mufutau@shanbaypro.com",
        "amanda@shanbaypro.com",
        "lev@shanbaypro.com",
    ],
    "isaac@shanbaypro.com": [
        "dustin@shanbaypro.com",
        "kay@shanbaypro.com",
        "colton@shanbaypro.com",
        "grady@shanbaypro.com",
        "preston@shanbaypro.com",
        "christine@shanbaypro.com",
    ],
    "tatiana@shanbaypro.com": [
        "amos@shanbaypro.com",
        "cheng@shanbaypro.com",
        "ingrid@shanbaypro.com",
        "may@shanbaypro.com",
        "kim@shanbaypro.com",
    ],
    "lev@shanbaypro.com": [
        "cheng@shanbaypro.com",
        "christine@shanbaypro.com",
        "carol@shanbaypro.com",
        "cassady@shanbaypro.com",
        "shaine@shanbaypro.com",
        "holmes@shanbaypro.com",
    ],
    "lamar@shanbaypro.com": [
        "hedda@shanbaypro.com",
        "elton@shanbaypro.com",
        "colton@shanbaypro.com",
    ],
    "phoebe@shanbaypro.com": [
        "cheryl@shanbaypro.com",
        "moses@shanbaypro.com",
        "ursula@shanbaypro.com",
        "paki@shanbaypro.com",
    ],
    "ezekiel@shanbaypro.com": ["zeus@shanbaypro.com", "mohammad@shanbaypro.com"],
    "hedwig@shanbaypro.com": [
        "kiann@shanbaypro.com",
        "alexander@shanbaypro.com",
        "holmes@shanbaypro.com",
        "curran@shanbaypro.com",
    ],
    "cade@shanbaypro.com": ["alexandra@shanbaypro.com", "cheryl@shanbaypro.com"],
    "burton@shanbaypro.com": [
        "cheryl@shanbaypro.com",
        "karina@shanbaypro.com",
        "ruth@shanbaypro.com",
        "colton@shanbaypro.com",
        "jerry@shanbaypro.com",
        "jayesh@shanbaypro.com",
        "kim@shanbaypro.com",
    ],
    "amos@shanbaypro.com": [
        "george@shanbaypro.com",
        "raja@shanbaypro.com",
        "tatiana@shanbaypro.com",
        "stone@shanbaypro.com",
    ],
    "shea@shanbaypro.com": [
        "theodore@shanbaypro.com",
        "rama@shanbaypro.com",
        "ella@shanbaypro.com",
        "daria@shanbaypro.com",
    ],
    "stone@shanbaypro.com": [
        "amos@shanbaypro.com",
        "daniel@shanbaypro.com",
        "daria@shanbaypro.com",
        "kamal@shanbaypro.com",
        "byron@shanbaypro.com",
        "kiann@shanbaypro.com",
    ],
    "cassady@shanbaypro.com": [
        "may@shanbaypro.com",
        "kiann@shanbaypro.com",
        "naomi@shanbaypro.com",
        "grady@shanbaypro.com",
        "joshua@shanbaypro.com",
        "hunter@shanbaypro.com",
        "lev@shanbaypro.com",
    ],
    "nomlanga@shanbaypro.com": [
        "aladdin@shanbaypro.com",
        "alexander@shanbaypro.com",
        "zeus@shanbaypro.com",
        "holmes@shanbaypro.com",
        "amanda@shanbaypro.com",
        "raya@shanbaypro.com",
    ],
    "raya@shanbaypro.com": ["nomlanga@shanbaypro.com", "dolan@shanbaypro.com"],
    "jayesh@shanbaypro.com": [
        "adam@shanbaypro.com",
        "burton@shanbaypro.com",
        "graham@shanbaypro.com",
        "demetrius@shanbaypro.com",
        "richard@shanbaypro.com",
    ],
    "kim@shanbaypro.com": [
        "burton@shanbaypro.com",
        "tatiana@shanbaypro.com",
        "aladdin@shanbaypro.com",
        "tatum@shanbaypro.com",
    ],
    "chao@shanbaypro.com": ["paki@shanbaypro.com"],
    "eshan@shanbaypro.com": [
        "byron@shanbaypro.com",
        "mason@shanbaypro.com",
        "ingrid@shanbaypro.com",
        "sage@shanbaypro.com",
        "dustin@shanbaypro.com",
        "christine@shanbaypro.com",
    ],
    "kiann@shanbaypro.com": [
        "ella@shanbaypro.com",
        "zephania@shanbaypro.com",
        "moses@shanbaypro.com",
        "stone@shanbaypro.com",
        "daria@shanbaypro.com",
        "hedda@shanbaypro.com",
        "hedwig@shanbaypro.com",
        "cassady@shanbaypro.com",
    ],
    "eldece@shanbaypro.com": [
        "hamza@shanbaypro.com",
        "matthew@shanbaypro.com",
        "susan@shanbaypro.com",
        "ella@shanbaypro.com",
        "colton@shanbaypro.com",
    ],
    "hamza@shanbaypro.com": [
        "colton@shanbaypro.com",
        "hoyt@shanbaypro.com",
        "mufutau@shanbaypro.com",
        "simone@shanbaypro.com",
        "eldece@shanbaypro.com",
    ],
    "cheng@shanbaypro.com": [
        "neil@shanbaypro.com",
        "richard@shanbaypro.com",
        "alexander@shanbaypro.com",
        "tatiana@shanbaypro.com",
        "lev@shanbaypro.com",
    ],
    "sahil@shanbaypro.com": [
        "richard@shanbaypro.com",
        "daria@shanbaypro.com",
        "bree@shanbaypro.com",
        "cheryl@shanbaypro.com",
        "ella@shanbaypro.com",
    ],
}


def find_shortest_path(graph, start, end, shortestLength=-1, path=None):
    if path == None:
        path = []
    path = path + [start]
    if start == end:
        return path

    shortest = None
    for node in graph[start]:
        if node not in path:
            if shortestLength == -1 or len(path) < (shortestLength - 1):
                newpath = find_shortest_path(graph, node, end, shortestLength, path)
                if newpath:
                    if not shortest or len(newpath) < len(shortest):
                        shortest = newpath
                        shortestLength = len(newpath)
    return shortest

member1 = "hamza@shanbaypro.com"
member2 = "holmes@shanbaypro.com"
print("成员 1: " + member1)
print("成员 2: " + member2)
print("找寻最短路径... ")
path = find_shortest_path(sender_receiver, member1, member2)
print("邮件链条: " + "{}层关系".format(len(path) - 1))
print(path)
